name: "p4c-dpdk-ptf-tests"

on:
  push:
    branches:
      - wrap-up
  pull_request:
    branches:
      - wrap-up
      
concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: build_p4sde_ci-${{ github.ref }}
  cancel-in-progress: true

# Envs for infrap4d and dpdk libs
env:
    SDE: ${{ github.workspace }}
    P4C_DIR: ${{ github.workspace }}/p4c
    SDE_INSTALL: ${{ github.workspace }}/sde_install
    IPDK_RECIPE: ${{ github.workspace }}/ipdk.recipe
    DEPEND_INSTALL: ${{ github.workspace }}/dep_install

jobs:
  build_p4dpdk_ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: 'ccache'
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ptf-${{ runner.os }}-test
          max-size: 1000M

      - name: checkout P4C
        uses: actions/checkout@v3
        with:
             path: p4c
             submodules: recursive

    
      - name: Build p4c with only the DPDK backend
        working-directory: p4c
        run: |
          sudo -E tools/dpdk-ci-build.sh $P4C_DIR $IPDK_RECIPE $SDE_INSTALL $DEPEND_INSTALL

      - name: 'Run DPDK PTF tests'
        working-directory: p4c/build
        run: |
             sudo $IPDK_RECIPE/install/sbin/copy_config_files.sh $IPDK_RECIPE/install $SDE_INSTALL
             sudo $IPDK_RECIPE/install/sbin/set_hugepages.sh
             sudo -E ctest --output-on-failure --schedule-random -R dpdk-ptf*
