name: "p4c-dpdk-ptf-tests"

on:
  push:
    branches:
      - wrap-up
  pull_request:
    branches:
      - wrap-up
      
concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: build_p4sde_ci-${{ github.ref }}
  cancel-in-progress: true

# Envs for infrap4d and dpdk libs
env:
    SDE: ${{ github.workspace }}
    P4C_DIR: ${{ github.workspace }}/p4c
    SDE_INSTALL: ${{ github.workspace }}/sde_install
    IPDK_RECIPE: ${{ github.workspace }}/ipdk.recipe
    DEPEND_INSTALL: ${{ github.workspace }}/dep_install

jobs:
  build_p4dpdk_ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: 'ccache'
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ptf-${{ runner.os }}-test
          max-size: 1000M

      - name: 'Checkout'
        run: |
          echo "ls /usr/bin -R"
          ls /usr/bin -R
          echo "ls /usr/local/bin -R"
          ls /usr/local/bin -R
          echo "ls /usr/lib/x86_64-linux-gnu/"
          ls /usr/lib/x86_64-linux-gnu/
