name: "PTF-backend"

on:
  push:
    branches:
      - ptf_backend
  pull_request:
    branches:
      - ptf_backend
      
concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: p4c_ptf-${{ github.ref }}
  cancel-in-progress: true

env:
    SDE: ${{ github.workspace }}
    P4C_DIR: ${{ github.workspace }}/p4c

jobs:
  build_p4dpdk_ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: 'ccache'
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ptf-${{ runner.os }}-test
          max-size: 1000M

      - name: checkout P4C
        uses: actions/checkout@v3
        with:
             path: p4c
             submodules: recursive

      - name: Build p4c with only the DPDK backend and p4tools
        working-directory: p4c
        run: |
          sudo -E tools/dpdk-ci-build.sh $P4C_DIR $P4C_DIR $P4C_DIR $P4C_DIR

      - name: Generate tests
        working-directory: p4c
        run: |
          cd ./testdata/p4_16_samples
          ../../build/p4testgen --target dpdk --arch pna --max-tests 0 --out-dir $PWD --test-backend PTF $PWD/pna-dpdk-small_sample.p4
          cat ./pna-dpdk-small_sample.py

      - name: Run tests
        working-directory: p4c/build
        run: |
          sudo -E ctest --output-on-failure --schedule-random -R dpdk-ptf* 

          


